### ISSUE TITLE
Mediapipe face_landmark.tflite model conversion error

### ISSUE THREAD

**Issue by psiydown** [zhenhuaw-me/tflite2onnx#85]
Mediapipe model: https://storage.googleapis.com/mediapipe-assets/face_landmark.tflite
tflite2onnx face_landmark.tflite face_landmark.onnx
Error prompt:
Data type float16 not supported/tested yet, the generated model may contain error
Data type float16 not supported/tested yet, the generated model may contain error
Data type float16 not supported/tested yet, the generated model may contain error
Data type float16 not supported/tested yet, the generated model may contain error
Data type float16 not supported/tested yet, the generated model may contain error
Traceback (most recent call last):
File "N:\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "N:\anaconda3\lib\runpy.py", line 87, in run_code
exec(code, run_globals)
File "N:\anaconda3\Scripts\tflite2onnx.exe_main.py", line 7, in
File "N:\anaconda3\lib\site-packages\tflite2onnx\convert.py", line 58, in cmd_convert
convert(args.tflite_path, args.onnx_path)
File "N:\anaconda3\lib\site-packages\tflite2onnx\convert.py", line 44, in convert
model.convert(explicit_layouts)
File "N:\anaconda3\lib\site-packages\tflite2onnx\model.py", line 42, in convert
g.convert(explicit_layouts)
File "N:\anaconda3\lib\site-packages\tflite2onnx\graph.py", line 102, in convert
self._propagateLayout()
File "N:\anaconda3\lib\site-packages\tflite2onnx\graph.py", line 173, in _propagateLayout
t.transform()
File "N:\anaconda3\lib\site-packages\tflite2onnx\tensor.py", line 126, in transform
self.shape = self.layout.transform(self.shape)
File "N:\anaconda3\lib\site-packages\tflite2onnx\layout.py", line 27, in transform
output = transform(input, self.source, self.target)
File "N:\anaconda3\lib\site-packages\tflite2onnx\layout.py", line 16, in transform
transfrom_axis = [input[p] for p in perm]
File "N:\anaconda3\lib\site-packages\tflite2onnx\layout.py", line 16, in
transfrom_axis = [input[p] for p in perm]
IndexError: list index out of range

@zhenhuaw-me Can you give me any help? Thank you

**Comment by Kinbon** [comment]
> Mediapipe model: https://storage.googleapis.com/mediapipe-assets/face_landmark.tflite tflite2onnx face_landmark.tflite face_landmark.onnx Error prompt: Data type float16 not supported/tested yet, the generated model may contain error Data type float16 not supported/tested yet, the generated model may contain error Data type float16 not supported/tested yet, the generated model may contain error Data type float16 not supported/tested yet, the generated model may contain error Data type float16 not supported/tested yet, the generated model may contain error Traceback (most recent call last): File "N:\anaconda3\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "N:\anaconda3\lib\runpy.py", line 87, in run_code exec(code, run_globals) File "N:\anaconda3\Scripts\tflite2onnx.exe_main.py", line 7, in File "N:\anaconda3\lib\site-packages\tflite2onnx\convert.py", line 58, in cmd_convert convert(args.tflite_path, args.onnx_path) File "N:\anaconda3\lib\site-packages\tflite2onnx\convert.py", line 44, in convert model.convert(explicit_layouts) File "N:\anaconda3\lib\site-packages\tflite2onnx\model.py", line 42, in convert g.convert(explicit_layouts) File "N:\anaconda3\lib\site-packages\tflite2onnx\graph.py", line 102, in convert self._propagateLayout() File "N:\anaconda3\lib\site-packages\tflite2onnx\graph.py", line 173, in _propagateLayout t.transform() File "N:\anaconda3\lib\site-packages\tflite2onnx\tensor.py", line 126, in transform self.shape = self.layout.transform(self.shape) File "N:\anaconda3\lib\site-packages\tflite2onnx\layout.py", line 27, in transform output = transform(input, self.source, self.target) File "N:\anaconda3\lib\site-packages\tflite2onnx\layout.py", line 16, in transform transfrom_axis = [input[p] for p in perm] File "N:\anaconda3\lib\site-packages\tflite2onnx\layout.py", line 16, in transfrom_axis = [input[p] for p in perm] IndexError: list index out of range
> 
> @zhenhuaw-me Can you give me any help? Thank you

Excuse me.Have you got any idea about solving this issue?

**Comment by gokes001** [comment]
I'm facing the same issue. Any update/solution on this bug?
